openapi: 3.0.0
info:
  title: Netris API
  version: v2
security:
  - cookieAuth: []
paths:
  /api/v2/dhcp-option-set:
    get:
      tags:
        - DHCP Option Sets
      summary: Request for getting DHCP option sets.
      parameters:
        - name: filterBySites
          in: query
          description: ''
          schema:
            $ref: '#/components/schemas/filterBySites'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/resOKBody'
                  - type: object
                    properties:
                      errors:
                        example: null
                      message:
                        example: ''
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resErrorBody'
    post:
      tags:
        - DHCP Option Sets
      summary: Request for adding DHCP option sets.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DHCPOptionSetItem'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/resOKBody'
                  - type: object
                    properties:
                      message:
                        example: Successfully created
                      errors:
                        example: null
                      data:
                        example:
                          - id: 2
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resErrorBody'
  /api/v2/dhcp-option-set/{id}:
    get:
      tags:
        - DHCP Option Sets
      summary: Request for getting L4 Load Balancer Net.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The id of a specific L4LB
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/resOKBody'
                  - type: object
                    properties:
                      errors:
                        example: null
                      message:
                        example: ''
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resErrorBody'
        '404':
          description: Error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/resErrorBody'
                  - type: object
                    properties:
                      errors:
                        example:
                          property_name: Not Found
                      message:
                        example: Not found
                      meta:
                        properties:
                          statusCode:
                            example: 404
    put:
      tags:
        - DHCP Option Sets
      summary: Request for editing DHCP option sets.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The id of a specific DHCP option set
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DHCPOptionSetItem'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/resOKBody'
                  - type: object
                    properties:
                      message:
                        example: Successfully updated
                      errors:
                        example: null
                      data:
                        example:
                          - id: 2
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resErrorBody'
        '404':
          description: Error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/resErrorBody'
                  - type: object
                    properties:
                      errors:
                        example:
                          property_name: Not Found
                      message:
                        example: Not found
                      meta:
                        properties:
                          statusCode:
                            example: 404
    delete:
      tags:
        - DHCP Option Sets
      summary: Request for deleting DHCP option set.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The id of a specific DHCP option set
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/resOKBody'
                  - type: object
                    properties:
                      message:
                        example: Successfully deleted
                      errors:
                        example: null
                      data:
                        example:
                          - id: 2
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resErrorBody'
        '404':
          description: Error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/resErrorBody'
                  - type: object
                    properties:
                      errors:
                        example:
                          property_name: Not Found
                      message:
                        example: Not found
                      meta:
                        properties:
                          statusCode:
                            example: 404
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: Web Service Cookie
  schemas:
    DHCPOptionSetItem:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: mydhcpset
        description:
          type: string
          example: My DHCP set
        default:
          type: string
          enum:
          - no
          - yes
        domain_name:
          type: string
          default: ''
          example: example.com
        dns_servers:
          default: []
          type: array
          items:
            type: string
          example:
            - 8.8.8.8
            - 1.1.1.1
        ntp_servers:
          default: []
          type: array
          items:
            type: string
          example:
            - pool.ntp.org
            - 132.163.96.5
        lease_time:
          default: 86400
          type: integer
          example: 604800
          minimum: 600
          maximum: 4294967295
        additionalOptions:
          type: array
          default: []
          items:
            $ref: '#/components/schemas/DHCPOptionSetAdditionalOptionsItem'
          example:
            - code: 72
              value: 10.254.131.34
              type: text
    DHCPOptionSetItemWithID:
      allOf:
        - type: object
          properties:
            id:
              type: integer
              example: 1231
        - $ref: '#/components/schemas/DHCPOptionSetItem'
    DHCPOptionSetAdditionalOptionsItem:
      type: object
      properties:
        code:
          type: integer
        value:
          type: string
        type:
          type: string
          enum:
            - string
            - boolean
            - uin8
            - uint16
            - uint32
            - int8
            - int16
            - int32
            - ipv4-address
            - fqdn
    filterBySites:
      type: array
      items:
        $ref: '#/components/schemas/selectedSite'
    selectedSite:
      type: integer
    resErrorBody:
      type: object
      description: Error response
      properties:
        data:
          type: array
          items:
            type: object
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
          example: Error message
        isSuccess:
          type: boolean
          example: false
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 400
    resOKBody:
      type: object
      description: Success response
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/DHCPOptionSetItemWithID'
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
        isSuccess:
          type: boolean
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 200
