openapi: 3.0.0
info:
  title: Netris API
  version: v2
security:
  - cookieAuth: []
paths:
  /api/v2/inventoryProfiles:
    get:
      tags:
        - Inventory Profiles
      summary: Request for getting Inventory Profiles.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successResponse'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
    post:
      tags:
        - Inventory Profiles
      summary: Request for adding Inventory Profile.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inventoryProfileBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successResponse'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /api/v2/inventoryProfiles/{id}:
    get:
      tags:
        - Inventory Profiles
      summary: Request for getting Inventory Profile.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The id of a Inventory Profile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successResponse'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
    put:
      tags:
        - Inventory Profiles
      summary: Request for editting Inventory Profiles.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The id of a specific Inventory Profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inventoryProfileBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successResponse'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
    delete:
      tags:
        - Inventory Profiles
      summary: Request for deleting Inventory Profiles.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the Inventory Profile.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successResponse'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /api/v2/inventoryProfiles/{id}/hardwares:
    get:
      tags:
        - Inventory Profiles
      summary: Request for getting hardwares list.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The id of a specific Inventory Profile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/successResponse'
                  - type: object
                    properties:
                      data:
                        example: []
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: Web Service Cookie
  schemas:
    inventoryProfileItem:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: name
        description:
          type: string
          example: description
        siteId:
          type: integer
          example: 1
        ipv4_ssh:
          type: string
          example: 0.0.0.0/0,10.254.128.0/24
        ipv6_ssh:
          type: string
          example: '::/0'
        timezone:
          type: string
          example: '{"offset":"+04:00","label":"(GMT+04:00) Yerevan","tzCode":"Asia/Yerevan"}'
        ntp_servers:
          type: string
          example: 62.159.200.1,162.159.200.123,195.43.74.123,am.pool.ntp.org
        dns_servers:
          type: string
          example: 1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4
        customRules:
          type: array
          items:
            $ref: '#/components/schemas/customRule'
        createdDate:
          type: integer
        modifiedDate:
          type: integer
    inventoryProfileBody:
      type: object
      required:
        - name
        - ipv4_list
      properties:
        name:
          type: string
          example: name
        description:
          type: string
          example: description
        ipv4_list:
          type: string
          example: 0.0.0.0/0,10.254.128.0/24
        ipv6_list:
          type: string
          example: ''
        timezone:
          type: object
          properties:
            offset:
              type: string
              example: '+04:00'
            label:
              type: string
              example: (GMT+04:00) Yerevan
            tzCode:
              type: string
              example: Asia/Yerevan
        ntp_servers:
          type: string
          example: 0.0.0.0,10.254.128.0
        dns_servers:
          type: string
          example: ''
        customRules:
          type: array
          items:
            $ref: '#/components/schemas/customRule'
    customRule:
      type: object
      properties:
        id:
          type: integer
          description: Required on edit
          example: 1
        description:
          type: string
          example: Custom rule example
        srcSubnet:
          type: string
          example: 10.0.0.0
        srcPort:
          type: string
          example: '54'
        dstPort:
          type: string
          example: ''
        protocol:
          type: string
          enum:
            - tcp
            - udp
            - any
    successResponse:
      type: object
      description: Success response
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/inventoryProfileItem'
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
        isSuccess:
          type: boolean
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 200
    errorResponse:
      type: object
      description: Error response
      properties:
        data:
          type: array
          items:
            type: object
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
          example: Error message
        isSuccess:
          type: boolean
          example: false
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 400
