openapi: 3.0.0
info:
  title: Netris API
  version: v2
security:
  - cookieAuth: []
paths:
  /api/v2/l4lb:
    get:
      tags:
        - L4 Load Balancer
      summary: Request for getting L4 Load Balancers.
      parameters:
        - name: filterBySites
          in: query
          description: Filter by site id
          schema:
            type: array
            items:
              type: number
        - name: filterByVpc
          in: query
          description: Filter by vpc id.
          schema:
            type: array
            items:
              type: number
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resBody'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resErrorBody'
    post:
      tags:
        - L4 Load Balancer
      summary: Request for adding L4 Load Balancer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/l4lbAddItem'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resAddEditBody'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resErrorBody'
  /api/v2/l4lb/{id}:
    get:
      tags:
        - L4 Load Balancer
      summary: Request for getting L4 Load Balancer Net.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The id of a specific L4LB
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resBodyByID'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resErrorBody'
        '404':
          description: Error
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/resErrorBody'
                - type: object
                  properties:
                    message:
                      example: Not found.
                    meta:
                      properties:
                        statusCode:
                          example: 404
    put:
      tags:
        - L4 Load Balancer
      summary: Request for editing L4 Load Balancer.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The id of a specific L4LB
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/l4lbEditItem'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resAddEditBody'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resErrorBody'
        '404':
          description: Error
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/resErrorBody'
                - type: object
                  properties:
                    message:
                      example: Not found.
                    meta:
                      properties:
                        statusCode:
                          example: 404
    delete:
      tags:
        - L4 Load Balancer
      summary: Request for deleting L4 Load Balancer.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The id of a specific L4LB
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resDeleteBody'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resErrorBody'
        '404':
          description: Error
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/resErrorBody'
                - type: object
                  properties:
                    message:
                      example: Not found.
                    meta:
                      properties:
                        statusCode: 
                          example: 404
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: Web Service Cookie
  schemas:
    L4LoadBalancerItem:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: name
        vpc:
          type: object
          properties:
            id:
              type: integer
              example: 1
            name:
              type: string
              example: Default
          description: When vpc object is null the rule will be created in Default VPC.
        site:
          type: object
          properties:
            id:
              type: integer
              example: 11
            name:
              type: string
              example: Santa-Clara
        tenant:
          type: object
          properties:
            id:
              type: number
              example: 1
            name:
              type: string
              example: Admin
        protocol:
          type: string
          enum:
            - TCP
            - UDP
          example: TCP
        ipFamily:
          type: string
          enum:
            - IPv4
            - IPv6
        ip:
          type: string
          example: 169.254.254.253
        port:
          type: integer
          example: 443
        healthcheck:
          type: object
          properties:
            protocol:
              type: string
              enum:
                - TCP
                - HTTP
            timeout:
              type: integer
            requestPath:
              type: string
          example:
            HTTP:
              timeOut: 1000
              requestPath: '/health'
        status:
          type: string
          enum:
            - enable
            - disable
          example: enable
        internal:
          type: integer
          example: 0
        tenantId:
          type: integer
          example: "Deprecated: please use tenant object instead"
        tenantName:
          type: string
          example: "Deprecated: please use tenant object instead"
        siteId:
          type: integer
          example: "Deprecated: please use site object instead"
        siteName:
          type: string
          example: "Deprecated: please use site object instead"
        backendIps:
          type: array
          items:
            $ref: '#/components/schemas/L4LoadBalancerBackendItemResponse'
    l4lbAddItem:
      type: object
      properties:
        name:
          type: string
          example: name
          description: unique name
        vpc:
          type: object
          properties:
            id:
              type: integer
              example: 1
          description: When vpc object is null the rule will be created in Default VPC.
        site:
          type: object
          properties:
            id:
              type: integer
              example: 11
        tenant:
          type: object
          properties:
            id:
              type: number
              example: 1
        protocol:
          type: string
          example: TCP
          description: TCP/UDP
        automatic:
          type: boolean
          enum:
            - true
            - false
        ipFamily:
          type: string
          enum:
            - IPv4
            - IPv6
        ip:
          type: string
          example: 1.1.1.1
        status:
          type: string
          example: enable
          description: enable/disable
        healthCheck:
          enum:
            - None
            - TCP
            - HTTP
          type: string
          description: only with TCP protocol (TCP, HTTP, None)
        timeOut:
          type: string
          example: 1000
          description: only with TCP protocol
        requestPath:
          type: string
          description: only with TCP protocol
        backend:
          type: array
          items:
            $ref: '#/components/schemas/L4LoadBalancerBackend'
        tenantID:
          type: number
          example: "Deprecated: use tenant object instead"
        siteID:
          type: number
          example: "Deprecated: use site object instead"
    l4lbEditItem:
      type: object
      properties:
        name:
          type: string
          example: name
          description: unique name
        vpc:
          type: object
          properties:
            id:
              type: integer
              example: 1
          description: When vpc object is null the rule will be created in Default VPC.
        site:
          type: object
          properties:
            id:
              type: integer
              example: 11
        tenant:
          type: object
          properties:
            id:
              type: number
              example: 1
        protocol:
          type: string
          example: TCP
          description: TCP/UDP
        automatic:
          type: boolean
          example: 'true'
          description: true/false
        ip:
          type: string
          example: 1.1.1.1
        status:
          type: string
          example: enable
          description: enable/disable
        healthCheck:
          type: string
          example: TCP
          description: only with TCP protocol (TCP, HTTP, None)
        timeOut:
          type: string
          example: 1000
          description: only with TCP protocol
        requestPath:
          type: string
          description: only with TCP protocol
        tenantID:
          type: number
          example: "Deprecated: use tenant object instead"
        siteID:
          type: number
          example: "Deprecated: use site object instead"
        backend:
          type: array
          items:
            $ref: '#/components/schemas/L4LoadBalancerBackend'
    L4LoadBalancerBackend:
      type: array
      items:
        $ref: '#/components/schemas/L4LoadBalancerBackendItem'
    L4LoadBalancerBackendItem:
      type: object
      properties:
        ip:
          type: string
          example: 10.0.0.0
        port:
          type: integer
          example: 8080
        maintenance:
          type: boolean
          enum:
            - true
            - false
          example: false
      required:
        - ip
        - port
        - maintenance
    L4LoadBalancerBackendAdd:
      type: array
      items:
        $ref: '#/components/schemas/L4LoadBalancerBackendAddItem'
    L4LoadBalancerBackendAddItem:
      type: object
      properties:
        ip:
          type: string
        port:
          type: number
          example: number
        maintenance:
          type: boolean
          description: true/false
      required:
        - ip
        - port
        - maintenance
    L4LoadBalancerBackendItemResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        ip:
          type: string
          example: 10.0.0.0
        port:
          type: integer
          example: 8080
        maintenance:
          type: boolean
          enum:
            - true
            - false
          example: false
        stats:
          type: array
          items:
            type: object
            properties:
              hardware:
                type: object
                properties:
                  id:
                    type: integer
                    example: 123
                  name:
                    type: string
                    example: Softgate01
              status:
                type: string
                enum:
                  - ok
                  - failed
                example: failed
              response:
                type: string
                example: connection refused
    resBody:
      type: object
      description: Success response
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/L4LoadBalancerItem'
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
        isSuccess:
          type: boolean
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 200
    resBodyByID:
      type: object
      description: Success response
      properties:
        data:
          $ref: '#/components/schemas/L4LoadBalancerItem'
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
        isSuccess:
          type: boolean
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 200
    resAddEditBody:
      type: object
      description: Success response
      properties:
        data:
          type: object
          properties:
            id:
              type: integer
              example: 2
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
          example: ''
        isSuccess:
          type: boolean
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 200
    resDeleteBody:
      type: object
      description: Success response
      properties:
        data:
          type: object
          nullable: true
          example: null
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
          example: ''
        isSuccess:
          type: boolean
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 200
    resErrorBody:
      type: object
      description: Error response
      properties:
        data:
          type: object
          nullable: true
          example: null
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
          example: Error message
        isSuccess:
          type: boolean
          example: false
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 400
